In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/cybersecurity.csv")

In [3]:
keep_features = [
    "src_port",
    "dst_port",
    "protocol",
    "bytes_sent",
    "bytes_received",
    "user_agent",
    "is_internal_traffic"
]
keep_features

['src_port',
 'dst_port',
 'protocol',
 'bytes_sent',
 'bytes_received',
 'user_agent',
 'is_internal_traffic']

In [4]:
cleaned_df = df[keep_features].copy()

In [5]:
cleaned_df.head()

,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,is_internal_traffic
0,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False
1,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False
2,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,False
3,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False
4,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False

In [6]:
cleaned_df.tail()

,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,is_internal_traffic
9995,43285,3306,UDP,1053,401,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False
9996,3389,445,TCP,10597,16670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,False
9997,18395,53,TCP,2857,6031,sqlmap/1.8,False
9998,31882,80,TCP,6062,3504,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,False
9999,52607,3389,TCP,335446,442720,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,False

In [7]:
numeric_features = ["src_port" , "dst_port" , "protocol" , "bytes_sent" , "bytes_received"]
categorical_features = ["protocol" , "is_internal_traffic" , "user_agent"]

In [8]:
numeric_features

['src_port', 'dst_port', 'protocol', 'bytes_sent', 'bytes_received']

In [9]:
categorical_features

['protocol', 'is_internal_traffic', 'user_agent']

In [10]:
cleaned_df.isna().sum()

src_port               0
dst_port               0
protocol               0
bytes_sent             0
bytes_received         0
user_agent             0
is_internal_traffic    0
dtype: int64

In [11]:
cleaned_df.dtypes

src_port               int64
dst_port               int64
protocol                 str
bytes_sent             int64
bytes_received         int64
user_agent               str
is_internal_traffic     bool
dtype: object

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
onehot_features = [
    "protocol",
    "user_agent"
]

In [14]:
encoder = OneHotEncoder( handle_unknown="ignore")
#means that the encoder learns from the categories from the training data so when he gets new data not in the category he learned the "handle_unknown="ignore" makes him ignore it and handle it

In [15]:
encoder.fit(cleaned_df[onehot_features]) # fit to learn from the data

OneHotEncoder(handle_unknown='ignore')

In [16]:
encoded_data = encoder.transform(cleaned_df[onehot_features]) # to transform them to 0 , 1 
encoded_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20000 stored elements and shape (10000, 16)>

In [17]:
encoder.get_feature_names_out()

array(['protocol_ICMP', 'protocol_TCP', 'protocol_UDP',
       'user_agent_Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
       'user_agent_Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
       'user_agent_Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
       'user_agent_Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
       'user_agent_Mozilla/5.0 (compatible; sqlmap/1.7)',
       'user_agent_Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
       'user_agent_curl/7.81.0', 'user_agent_curl/8.4.0',
       'user_agent_python-requests/2.28',
       'user_agent_python-requests/2.31.0',
       'user_agent_python-urllib/3.9', 'user_agent_sqlmap/1.8',
       'user_agent_zgrab/0.x'], dtype=object)

In [18]:
cleaned_df["is_internal_traffic"] = cleaned_df["is_internal_traffic"].astype(int)

In [19]:
y=df["label"]

In [ ]:
y.value_counts()
# 96% normal , 4% attack

label
0    9600
1     400
Name: count, dtype: int64

In [21]:
x = cleaned_df

In [23]:
x.shape

(10000, 7)

In [ ]:
stratify=y
# to maintain the same percent in the train_test_split  96% normal , , 4% attack

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train , x_test , y_train , y_test = train_test_split (x , y , test_size=0.2 , stratify=y , random_state=42)

In [29]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((8000, 7), (2000, 7), (8000,), (2000,))

In [30]:
from sklearn.compose import ColumnTransformer

In [31]:
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("num", "passthrough", numeric_features)
])

In [ ]:
numeric_features = [
    "src_port",
    "dst_port",
    "bytes_sent",
    "bytes_received",
    "is_internal_traffic"
]

categorical_features = [
    "protocol",
    "user_agent"
]
#just added is_internal_traffic ly el numerical 3shan khalas ba2a 0/1

In [33]:
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("num", "passthrough", numeric_features)
])

In [ ]:
preprocessor.fit(x_train) # now done he learned from the categories

ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['protocol', 'user_agent']),
                                ('num', 'passthrough',
                                 ['src_port', 'dst_port', 'bytes_sent',
                                  'bytes_received', 'is_internal_traffic'])])

In [35]:
x_train_processed = preprocessor.transform(x_train)

In [36]:
x_train_processed.shape

(8000, 21)

In [37]:
x_test_processed = preprocessor.transform(x_test)

In [38]:
x_test_processed.shape

(2000, 21)

In [39]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(class_weight="balanced" , random_state=42)

# class_weight="balanced" to give the attack=1 the minority class more weght during train

In [41]:
model.fit(x_train_processed , y_train)

c:\Users\hp\OneDrive\Desktop\cybersecurity-threat-detection\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
# we need to scale as in coulmn transformer we added passthrough  and in the last cell it gave a warning that it needs more iter than 100

In [43]:
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("num", StandardScaler(), numeric_features)
])

In [44]:
preprocessor.fit(x_train)

ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['protocol', 'user_agent']),
                                ('num', StandardScaler(),
                                 ['src_port', 'dst_port', 'bytes_sent',
                                  'bytes_received', 'is_internal_traffic'])])

In [47]:
x_train_processed = preprocessor.transform(x_train)

In [50]:
x_test_processed = preprocessor.transform(x_test)

In [51]:
x_test_processed.shape , x_train_processed.shape

((2000, 21), (8000, 21))

In [52]:
model = LogisticRegression(class_weight="balanced" , random_state=42 , max_iter=1000)

In [53]:
model.fit(x_train_processed , y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [54]:
y_pred = model.predict(x_test_processed)

In [55]:
y_pred

array([0, 1, 0, ..., 1, 0, 1], shape=(2000,))

In [56]:
y_pred.value_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [57]:
pd.Series(y_pred).value_counts()

0    1403
1     597
Name: count, dtype: int64

In [58]:
from sklearn.metrics import classification_report

In [59]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.98      0.72      0.83      1920
           1       0.10      0.72      0.17        80

    accuracy                           0.72      2000
   macro avg       0.54      0.72      0.50      2000
weighted avg       0.95      0.72      0.80      2000

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
cm = confusion_matrix(y_test , y_pred)
cm

array([[1381,  539],
       [  22,   58]])